### ISSUE TITLE
got error NumberFormatException 

### ISSUE THREAD

**Issue by smmousavi76** [EsperoTech/yaade#169]
got this error on openshift
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.NumberFormatException: For input string: "tcp://172.30.230.80:9339"
at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.base/java.lang.Integer.parseInt(Integer.java:652)
at java.base/java.lang.Integer.parseInt(Integer.java:770)
at com.espero.yaade.MainKt.<clinit>(Main.kt:10)

**Comment by jonrosner** [comment]
please explain in more detail when the problem occurs and provide a minimal reproducible example step by step
