### ISSUE TITLE
Issue importing OpenAPI file

### ISSUE THREAD

**Issue by AndyIsHereBoi** [EsperoTech/yaade#220]
```


yaade  | [vert.x-eventloop-thread-0] ERROR com.espero.yaade.server.Server - [Sun, 15 Dec 2024 03:19:27 GMT] "POST /api/collection/importOpenApi?basePath=&groups=admin HTTP_1_1" 500 Cannot invoke "io.swagger.v3.oas.models.Components.getSchemas()" because the return value of "io.swagger.v3.oas.models.OpenAPI.getComponents()" is null "http://10.0.1.203:9339/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:133.0) Gecko/20100101 Firefox/133.0"
yaade  | [vert.x-eventloop-thread-0] ERROR io.vertx.ext.web.handler.impl.LoggerHandlerImpl - 10.0.1.151 - - [Sun, 15 Dec 2024 03:19:27 GMT] "POST /api/collection/importOpenApi?basePath=&groups=admin HTTP/1.1" 500 15580 "http://10.0.1.203:9339/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:133.0) Gecko/20100101 Firefox/133.0"
yaade  | java.lang.NullPointerException: Cannot invoke "io.swagger.v3.oas.models.Components.getSchemas()" because the return value of "io.swagger.v3.oas.models.OpenAPI.getComponents()" is null
yaade  |        at com.espero.yaade.services.OpenApiService.createRequestsFromOpenApi(OpenApiService.kt:86)
yaade  |        at com.espero.yaade.server.routes.CollectionRoute.importOpenApiCollection(CollectionRoute.kt:278)
yaade  |        at com.espero.yaade.server.Server$restartServer$14.invoke(Server.kt:112)
yaade  |        at com.espero.yaade.server.Server$restartServer$14.invoke(Server.kt:112)
yaade  |        at com.espero.yaade.server.utils.VertxUtilsKt$authorizedCoroutineHandler$1$1.invokeSuspend(VertxUtils.kt:57)
yaade  |        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
yaade  |        at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
yaade  |        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
yaade  |        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
yaade  |        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
yaade  |        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
yaade  |        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
yaade  |        at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
yaade  |        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
yaade  |        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
yaade  |        at com.espero.yaade.server.utils.VertxUtilsKt.authorizedCoroutineHandler$lambda$1(VertxUtils.kt:55)
yaade  |        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1285)
yaade  |        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:140)
yaade  |        at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
yaade  |        at io.vertx.ext.web.validation.impl.ValidationHandlerImpl.lambda$handle$5(ValidationHandlerImpl.java:168)
yaade  |        at io.vertx.core.impl.future.SucceededFuture.onComplete(SucceededFuture.java:81)
yaade  |        at io.vertx.ext.web.validation.impl.ValidationHandlerImpl.handle(ValidationHandlerImpl.java:159)
yaade  |        at io.vertx.ext.web.validation.impl.ValidationHandlerImpl.handle(ValidationHandlerImpl.java:18)
yaade  |        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1285)
yaade  |        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:140)
yaade  |        at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
yaade  |        at io.vertx.ext.web.handler.impl.ResponseContentTypeHandlerImpl.handle(ResponseContentTypeHandlerImpl.java:54)
yaade  |        at io.vertx.ext.web.handler.impl.ResponseContentTypeHandlerImpl.handle(ResponseContentTypeHandlerImpl.java:28)
yaade  |        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1285)
yaade  |        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
yaade  |        at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
yaade  |        at io.vertx.ext.web.handler.impl.LoggerHandlerImpl.handle(LoggerHandlerImpl.java:189)
yaade  |        at io.vertx.ext.web.handler.impl.LoggerHandlerImpl.handle(LoggerHandlerImpl.java:48)
yaade  |        at com.espero.yaade.server.Server.restartServer$lambda$0(Server.kt:81)
yaade  |        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1285)
yaade  |        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:140)
yaade  |        at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
yaade  |        at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:359)
yaade  |        at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.uploadEnded(BodyHandlerImpl.java:325)
yaade  |        at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.lambda$null$0(BodyHandlerImpl.java:254)
yaade  |        at io.vertx.core.impl.future.FutureImpl$4.onSuccess(FutureImpl.java:176)
yaade  |        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:66)
yaade  |        at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:246)
yaade  |        at io.vertx.core.impl.future.Composition$1.onSuccess(Composition.java:62)
yaade  |        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:66)
yaade  |        at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:246)
yaade  |        at io.vertx.core.impl.future.Composition$1.onSuccess(Composition.java:62)
yaade  |        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:66)
yaade  |        at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:88)
yaade  |        at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:43)
yaade  |        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:66)
yaade  |        at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:246)
yaade  |        at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49)
yaade  |        at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:60)
yaade  |        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
yaade  |        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
yaade  |        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
yaade  |        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
yaade  |        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
yaade  |        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
yaade  |        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
yaade  |        at java.base/java.lang.Thread.run(Thread.java:840)
yaade  | java.lang.NullPointerException: Cannot invoke "io.swagger.v3.oas.models.Components.getSchemas()" because the return value of "io.swagger.v3.oas.models.OpenAPI.getComponents()" is null
yaade  |        at com.espero.yaade.services.OpenApiService.createRequestsFromOpenApi(OpenApiService.kt:86)
yaade  |        at com.espero.yaade.server.routes.CollectionRoute.importOpenApiCollection(CollectionRoute.kt:278)
yaade  |        at com.espero.yaade.server.Server$restartServer$14.invoke(Server.kt:112)
yaade  |        at com.espero.yaade.server.Server$restartServer$14.invoke(Server.kt:112)
yaade  |        at com.espero.yaade.server.utils.VertxUtilsKt$authorizedCoroutineHandler$1$1.invokeSuspend(VertxUtils.kt:57)
yaade  |        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
yaade  |        at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
yaade  |        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
yaade  |        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
yaade  |        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
yaade  |        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
yaade  |        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
yaade  |        at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
yaade  |        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
yaade  |        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
yaade  |        at com.espero.yaade.server.utils.VertxUtilsKt.authorizedCoroutineHandler$lambda$1(VertxUtils.kt:55)
yaade  |        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1285)
yaade  |        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:140)
yaade  |        at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
yaade  |        at io.vertx.ext.web.validation.impl.ValidationHandlerImpl.lambda$handle$5(ValidationHandlerImpl.java:168)
yaade  |        at io.vertx.core.impl.future.SucceededFuture.onComplete(SucceededFuture.java:81)
yaade  |        at io.vertx.ext.web.validation.impl.ValidationHandlerImpl.handle(ValidationHandlerImpl.java:159)
yaade  |        at io.vertx.ext.web.validation.impl.ValidationHandlerImpl.handle(ValidationHandlerImpl.java:18)
yaade  |        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1285)
yaade  |        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:140)
yaade  |        at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
yaade  |        at io.vertx.ext.web.handler.impl.ResponseContentTypeHandlerImpl.handle(ResponseContentTypeHandlerImpl.java:54)
yaade  |        at io.vertx.ext.web.handler.impl.ResponseContentTypeHandlerImpl.handle(ResponseContentTypeHandlerImpl.java:28)
yaade  |        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1285)
yaade  |        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
yaade  |        at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
yaade  |        at io.vertx.ext.web.handler.impl.LoggerHandlerImpl.handle(LoggerHandlerImpl.java:189)
yaade  |        at io.vertx.ext.web.handler.impl.LoggerHandlerImpl.handle(LoggerHandlerImpl.java:48)
yaade  |        at com.espero.yaade.server.Server.restartServer$lambda$0(Server.kt:81)
yaade  |        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1285)
yaade  |        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:140)
yaade  |        at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
yaade  |        at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:359)
yaade  |        at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.uploadEnded(BodyHandlerImpl.java:325)
yaade  |        at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.lambda$null$0(BodyHandlerImpl.java:254)
yaade  |        at io.vertx.core.impl.future.FutureImpl$4.onSuccess(FutureImpl.java:176)
yaade  |        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:66)
yaade  |        at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:246)
yaade  |        at io.vertx.core.impl.future.Composition$1.onSuccess(Composition.java:62)
yaade  |        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:66)
yaade  |        at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:246)
yaade  |        at io.vertx.core.impl.future.Composition$1.onSuccess(Composition.java:62)
yaade  |        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:66)
yaade  |        at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:88)
yaade  |        at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:43)
yaade  |        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:66)
yaade  |        at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:246)
yaade  |        at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49)
yaade  |        at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:60)
yaade  |        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
yaade  |        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
yaade  |        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
yaade  |        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
yaade  |        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
yaade  |        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
yaade  |        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
yaade  |        at java.base/java.lang.Thread.run(Thread.java:840)
yaade  | [vert.x-eventloop-thread-0] ERROR com.espero.yaade.server.Server - [Sun, 15 Dec 2024 03:20:21 GMT] "POST /api/collection/importOpenApi?basePath=&groups=admin HTTP_1_1" 500 Cannot invoke "io.swagger.v3.oas.models.Components.getSchemas()" because the return value of "io.swagger.v3.oas.models.OpenAPI.getComponents()" is null "http://10.0.1.203:9339/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:133.0) Gecko/20100101 Firefox/133.0"
yaade  | [vert.x-eventloop-thread-0] ERROR io.vertx.ext.web.handler.impl.LoggerHandlerImpl - 10.0.1.151 - - [Sun, 15 Dec 2024 03:20:21 GMT] "POST /api/collection/importOpenApi?basePath=&groups=admin HTTP/1.1" 500 15580 "http://10.0.1.203:9339/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:133.0) Gecko/20100101 Firefox/133.0"
```

**Comment by AndyIsHereBoi** [comment]
nevermind, i didnt see you didnt have to convert to openapi from postman and that there was a postman selector. this can be closed
