### ISSUE TITLE
Can't get OIDC w/ Authentik working

### ISSUE THREAD

**Issue by luketainton** [EsperoTech/yaade#42]
I'm following the docs for OpenID Connect but can't seem to get it to work with my Authentik deployment. 

If I set the provider config to this:
```json
{
  "providers": [{
    "id": "authentik",
    "label": "Sign in with Authentik",
    "provider": "oidc-discovery",
    "params": {
      "scopes": ["openid", "email"],
      "site": "https://<REDACTED>/application/o/yaade/.well-known/openid-configuration",
      "clientId": "<REDACTED>",
      "clientSecret": "<REDACTED>"
    }
  }]
}
```
Then I get the below error:
<img width="466" alt="Screenshot 2022-12-31 at 00 39 33" src="https://user-images.githubusercontent.com/22561713/210119927-7dee6673-b875-41ec-b5b5-416c937314ab.png">

But if I set the provider config to this (i.e. change the `site` param):
```json
{
  "providers": [{
    "id": "authentik",
    "label": "Sign in with Authentik",
    "provider": "oidc-discovery",
    "params": {
      "scopes": ["openid", "email"],
      "site": "https://<REDACTED>/application/o/yaade",
      "clientId": "<REDACTED>",
      "clientSecret": "<REDACTED>"
    }
  }]
}
```
Then I get the below error:
<img width="316" alt="Screenshot 2022-12-31 at 00 35 56" src="https://user-images.githubusercontent.com/22561713/210119830-f7f00c43-29ca-412c-bffd-75b665e6ceac.png">

Setting the `{"validateIssuer": false}` parameter as per the [API docs](https://vertx.io/docs/apidocs/io/vertx/ext/auth/oauth2/OAuth2Options.html#setValidateIssuer-boolean-) results in all attempts failing with `null` as shown in the second example.

**Comment by jonrosner** [comment]
You did not provide a callback config Maybe this examples helps:

```
{
        "id": "authentik",
        "provider": "oidc-discovery",
        "params": {
            "site": "http://localhost:9000/application/o/yaade",
            "clientId": "some-id",
            "clientSecret": "some-secret",
            "callback": {
                "url": "http://localhost:9339/callback-authentik",
                "path": "/callback-authentik"
            },
            "fields": {
                "username": "/preferred_username",
                "groups": "/groups",
                "defaultGroups": ["espero4"]
            }
        }
```

**Comment by luketainton** [comment]
That helped, thanks. Turns out I hadn't set the callback URL correctly. I do get a different issue now though, in the form of a stack trace:

```

{"cause":null,"stackTrace":[{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"handleFailure","fileName":"ServerError.kt","lineNumber":36,"className":"com.espero.yaade.server.errors.ServerErrorKt","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"handleFailure","fileName":"RouteState.java","lineNumber":1290,"className":"io.vertx.ext.web.impl.RouteState","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"iterateNext","fileName":"RoutingContextImplBase.java","lineNumber":170,"className":"io.vertx.ext.web.impl.RoutingContextImplBase","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"next","fileName":"RoutingContextWrapper.java","lineNumber":200,"className":"io.vertx.ext.web.impl.RoutingContextWrapper","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"handleFailure","fileName":"RouterImpl.java","lineNumber":256,"className":"io.vertx.ext.web.impl.RouterImpl","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"handleFailure","fileName":"RouteState.java","lineNumber":1290,"className":"io.vertx.ext.web.impl.RouteState","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"iterateNext","fileName":"RoutingContextImplBase.java","lineNumber":170,"className":"io.vertx.ext.web.impl.RoutingContextImplBase","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"next","fileName":"RoutingContextImpl.java","lineNumber":140,"className":"io.vertx.ext.web.impl.RoutingContextImpl","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"doFail","fileName":"RoutingContextImpl.java","lineNumber":543,"className":"io.vertx.ext.web.impl.RoutingContextImpl","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"fail","fileName":"RoutingContextImpl.java","lineNumber":192,"className":"io.vertx.ext.web.impl.RoutingContextImpl","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"fail","fileName":"RoutingContextImpl.java","lineNumber":181,"className":"io.vertx.ext.web.impl.RoutingContextImpl","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"lambda$null$2","fileName":"OAuth2AuthHandlerImpl.java","lineNumber":478,"className":"io.vertx.ext.web.handler.impl.OAuth2AuthHandlerImpl","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"onFailure","fileName":"FutureImpl.java","lineNumber":153,"className":"io.vertx.core.impl.future.FutureImpl$3","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"emitFailure","fileName":"FutureBase.java","lineNumber":75,"className":"io.vertx.core.impl.future.FutureBase","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"tryFail","fileName":"FutureImpl.java","lineNumber":230,"className":"io.vertx.core.impl.future.FutureImpl","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"onFailure","fileName":"Composition.java","lineNumber":66,"className":"io.vertx.core.impl.future.Composition$1","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"emitFailure","fileName":"FutureBase.java","lineNumber":75,"className":"io.vertx.core.impl.future.FutureBase","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"addListener","fileName":"FailedFuture.java","lineNumber":98,"className":"io.vertx.core.impl.future.FailedFuture","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"onFailure","fileName":"Composition.java","lineNumber":55,"className":"io.vertx.core.impl.future.Composition","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"emitFailure","fileName":"FutureBase.java","lineNumber":75,"className":"io.vertx.core.impl.future.FutureBase","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"tryFail","fileName":"FutureImpl.java","lineNumber":230,"className":"io.vertx.core.impl.future.FutureImpl","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"onFailure","fileName":"Composition.java","lineNumber":66,"className":"io.vertx.core.impl.future.Composition$1","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"emitFailure","fileName":"FutureBase.java","lineNumber":75,"className":"io.vertx.core.impl.future.FutureBase","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"addListener","fileName":"FailedFuture.java","lineNumber":98,"className":"io.vertx.core.impl.future.FailedFuture","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"onFailure","fileName":"Composition.java","lineNumber":55,"className":"io.vertx.core.impl.future.Composition","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"emitFailure","fileName":"FutureBase.java","lineNumber":75,"className":"io.vertx.core.impl.future.FutureBase","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"tryFail","fileName":"FutureImpl.java","lineNumber":230,"className":"io.vertx.core.impl.future.FutureImpl","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"onFailure","fileName":"Composition.java","lineNumber":66,"className":"io.vertx.core.impl.future.Composition$1","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"emitFailure","fileName":"FutureBase.java","lineNumber":75,"className":"io.vertx.core.impl.future.FutureBase","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"tryFail","fileName":"FutureImpl.java","lineNumber":230,"className":"io.vertx.core.impl.future.FutureImpl","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"onFailure","fileName":"Composition.java","lineNumber":66,"className":"io.vertx.core.impl.future.Composition$1","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"emitFailure","fileName":"FutureBase.java","lineNumber":75,"className":"io.vertx.core.impl.future.FutureBase","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"tryFail","fileName":"FutureImpl.java","lineNumber":230,"className":"io.vertx.core.impl.future.FutureImpl","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"onFailure","fileName":"Composition.java","lineNumber":66,"className":"io.vertx.core.impl.future.Composition$1","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"emitFailure","fileName":"FutureBase.java","lineNumber":75,"className":"io.vertx.core.impl.future.FutureBase","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"addListener","fileName":"FailedFuture.java","lineNumber":98,"className":"io.vertx.core.impl.future.FailedFuture","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"onSuccess","fileName":"Composition.java","lineNumber":43,"className":"io.vertx.core.impl.future.Composition","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"lambda$emitSuccess$0","fileName":"FutureBase.java","lineNumber":54,"className":"io.vertx.core.impl.future.FutureBase","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"execute","fileName":"EventLoopContext.java","lineNumber":87,"className":"io.vertx.core.impl.EventLoopContext","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"execute","fileName":"ContextImpl.java","lineNumber":260,"className":"io.vertx.core.impl.ContextImpl","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"execute","fileName":"EventLoopContext.java","lineNumber":23,"className":"io.vertx.core.impl.EventLoopContext","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"emitSuccess","fileName":"FutureBase.java","lineNumber":51,"className":"io.vertx.core.impl.future.FutureBase","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"tryComplete","fileName":"FutureImpl.java","lineNumber":211,"className":"io.vertx.core.impl.future.FutureImpl","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"tryComplete","fileName":"PromiseImpl.java","lineNumber":23,"className":"io.vertx.core.impl.future.PromiseImpl","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"handleEnd","fileName":"HttpEventHandler.java","lineNumber":79,"className":"io.vertx.core.http.impl.HttpEventHandler","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"handleEnd","fileName":"HttpClientResponseImpl.java","lineNumber":250,"className":"io.vertx.core.http.impl.HttpClientResponseImpl","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"lambda$new$0","fileName":"Http1xClientConnection.java","lineNumber":397,"className":"io.vertx.core.http.impl.Http1xClientConnection$StreamImpl","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"handleEvent","fileName":"InboundBuffer.java","lineNumber":240,"className":"io.vertx.core.streams.impl.InboundBuffer","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"write","fileName":"InboundBuffer.java","lineNumber":130,"className":"io.vertx.core.streams.impl.InboundBuffer","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"handleEnd","fileName":"Http1xClientConnection.java","lineNumber":624,"className":"io.vertx.core.http.impl.Http1xClientConnection$StreamImpl","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"execute","fileName":"EventLoopContext.java","lineNumber":77,"className":"io.vertx.core.impl.EventLoopContext","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"execute","fileName":"ContextImpl.java","lineNumber":267,"className":"io.vertx.core.impl.ContextImpl","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"handleResponseEnd","fileName":"Http1xClientConnection.java","lineNumber":858,"className":"io.vertx.core.http.impl.Http1xClientConnection","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"handleHttpMessage","fileName":"Http1xClientConnection.java","lineNumber":730,"className":"io.vertx.core.http.impl.Http1xClientConnection","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"handleMessage","fileName":"Http1xClientConnection.java","lineNumber":694,"className":"io.vertx.core.http.impl.Http1xClientConnection","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"read","fileName":"ConnectionBase.java","lineNumber":155,"className":"io.vertx.core.net.impl.ConnectionBase","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"channelRead","fileName":"VertxHandler.java","lineNumber":153,"className":"io.vertx.core.net.impl.VertxHandler","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"invokeChannelRead","fileName":"AbstractChannelHandlerContext.java","lineNumber":379,"className":"io.netty.channel.AbstractChannelHandlerContext","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"invokeChannelRead","fileName":"AbstractChannelHandlerContext.java","lineNumber":365,"className":"io.netty.channel.AbstractChannelHandlerContext","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"fireChannelRead","fileName":"AbstractChannelHandlerContext.java","lineNumber":357,"className":"io.netty.channel.AbstractChannelHandlerContext","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"fireChannelRead","fileName":"CombinedChannelDuplexHandler.java","lineNumber":436,"className":"io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"fireChannelRead","fileName":"ByteToMessageDecoder.java","lineNumber":327,"className":"io.netty.handler.codec.ByteToMessageDecoder","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"channelRead","fileName":"ByteToMessageDecoder.java","lineNumber":299,"className":"io.netty.handler.codec.ByteToMessageDecoder","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"channelRead","fileName":"CombinedChannelDuplexHandler.java","lineNumber":251,"className":"io.netty.channel.CombinedChannelDuplexHandler","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"invokeChannelRead","fileName":"AbstractChannelHandlerContext.java","lineNumber":379,"className":"io.netty.channel.AbstractChannelHandlerContext","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"invokeChannelRead","fileName":"AbstractChannelHandlerContext.java","lineNumber":365,"className":"io.netty.channel.AbstractChannelHandlerContext","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"fireChannelRead","fileName":"AbstractChannelHandlerContext.java","lineNumber":357,"className":"io.netty.channel.AbstractChannelHandlerContext","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"unwrap","fileName":"SslHandler.java","lineNumber":1372,"className":"io.netty.handler.ssl.SslHandler","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"decodeJdkCompatible","fileName":"SslHandler.java","lineNumber":1235,"className":"io.netty.handler.ssl.SslHandler","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"decode","fileName":"SslHandler.java","lineNumber":1284,"className":"io.netty.handler.ssl.SslHandler","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"decodeRemovalReentryProtection","fileName":"ByteToMessageDecoder.java","lineNumber":510,"className":"io.netty.handler.codec.ByteToMessageDecoder","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"callDecode","fileName":"ByteToMessageDecoder.java","lineNumber":449,"className":"io.netty.handler.codec.ByteToMessageDecoder","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"channelRead","fileName":"ByteToMessageDecoder.java","lineNumber":279,"className":"io.netty.handler.codec.ByteToMessageDecoder","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"invokeChannelRead","fileName":"AbstractChannelHandlerContext.java","lineNumber":379,"className":"io.netty.channel.AbstractChannelHandlerContext","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"invokeChannelRead","fileName":"AbstractChannelHandlerContext.java","lineNumber":365,"className":"io.netty.channel.AbstractChannelHandlerContext","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"fireChannelRead","fileName":"AbstractChannelHandlerContext.java","lineNumber":357,"className":"io.netty.channel.AbstractChannelHandlerContext","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"channelRead","fileName":"DefaultChannelPipeline.java","lineNumber":1410,"className":"io.netty.channel.DefaultChannelPipeline$HeadContext","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"invokeChannelRead","fileName":"AbstractChannelHandlerContext.java","lineNumber":379,"className":"io.netty.channel.AbstractChannelHandlerContext","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"invokeChannelRead","fileName":"AbstractChannelHandlerContext.java","lineNumber":365,"className":"io.netty.channel.AbstractChannelHandlerContext","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"fireChannelRead","fileName":"DefaultChannelPipeline.java","lineNumber":919,"className":"io.netty.channel.DefaultChannelPipeline","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"read","fileName":"AbstractNioByteChannel.java","lineNumber":166,"className":"io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"processSelectedKey","fileName":"NioEventLoop.java","lineNumber":722,"className":"io.netty.channel.nio.NioEventLoop","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"processSelectedKeysOptimized","fileName":"NioEventLoop.java","lineNumber":658,"className":"io.netty.channel.nio.NioEventLoop","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"processSelectedKeys","fileName":"NioEventLoop.java","lineNumber":584,"className":"io.netty.channel.nio.NioEventLoop","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"run","fileName":"NioEventLoop.java","lineNumber":496,"className":"io.netty.channel.nio.NioEventLoop","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"run","fileName":"SingleThreadEventExecutor.java","lineNumber":995,"className":"io.netty.util.concurrent.SingleThreadEventExecutor$4","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"run","fileName":"ThreadExecutorMap.java","lineNumber":74,"className":"io.netty.util.internal.ThreadExecutorMap$2","nativeMethod":false},{"classLoaderName":"app","moduleName":null,"moduleVersion":null,"methodName":"run","fileName":"FastThreadLocalRunnable.java","lineNumber":30,"className":"io.netty.util.concurrent.FastThreadLocalRunnable","nativeMethod":false},{"classLoaderName":null,"moduleName":"java.base","moduleVersion":"11.0.11","methodName":"run","fileName":"Thread.java","lineNumber":829,"className":"java.lang.Thread","nativeMethod":false}],"code":500,"message":"Moved Permanently","suppressed":[],"localizedMessage":"Moved Permanently"}
```

**Comment by jonrosner** [comment]
I just tried it with a clean installation of Yaade and Authentik (both inside of docker containers) and the following configuration:

```json
{
    "providers": [{
        "id": "authentik",
        "provider": "oidc-discovery",
        "params": {
            "site": "http://172.17.0.1:9000/application/o/yaade",
            "clientId": "some-id",
            "clientSecret": "some-secret",
            "callbackUrl": "http://localhost:9339/callback-yaade",
            "fields": {
                "username": "/sub",
                "groups": "/groups"
            }
        }
    }]
}
```

It works without a problem, so unfortunately I cannot replicate your problem.

**Comment by luketainton** [comment]
The only difference between your config and mine that I can see is that I'm using SSL. There is some talk about SSL in the latest stack trace I've got:
```
ServerError(code=400, message=Discovery failed: null)
	at com.espero.yaade.server.auth.AuthHandler.addOauth2Tenant(AuthHandler.kt:195)
	at com.espero.yaade.server.auth.AuthHandler.access$addOauth2Tenant(AuthHandler.kt:31)
	at com.espero.yaade.server.auth.AuthHandler$addOauth2Tenant$1.invokeSuspend(AuthHandler.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at io.vertx.kotlin.coroutines.VertxCoroutineExecutor.execute(VertxCoroutine.kt:229)
	at kotlinx.coroutines.ExecutorCoroutineDispatcherImpl.dispatch(Executors.kt:125)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:159)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
	at io.vertx.kotlin.coroutines.VertxCoroutineKt$await$2$1.handle(VertxCoroutine.kt:140)
	at io.vertx.kotlin.coroutines.VertxCoroutineKt$await$2$1.handle(VertxCoroutine.kt:138)
	at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153)
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230)
	at io.vertx.core.impl.future.Composition$1.onFailure(Composition.java:66)
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230)
	at io.vertx.core.impl.future.FixedMapping.onFailure(FixedMapping.java:36)
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230)
	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:40)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
	at io.vertx.core.impl.future.Composition$1.onSuccess(Composition.java:62)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:88)
	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:43)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
	at io.vertx.core.impl.future.Composition$1.onSuccess(Composition.java:62)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
	at io.vertx.core.impl.future.Composition$1.onSuccess(Composition.java:62)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
	at io.vertx.core.impl.future.Composition$1.onSuccess(Composition.java:62)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:88)
	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:43)
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:87)
	at io.vertx.core.impl.ContextImpl.execute(ContextImpl.java:260)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:23)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:51)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
	at io.vertx.core.http.impl.HttpEventHandler.handleEnd(HttpEventHandler.java:79)
	at io.vertx.core.http.impl.HttpClientResponseImpl.handleEnd(HttpClientResponseImpl.java:250)
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.lambda$new$0(Http1xClientConnection.java:397)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:240)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:130)
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.handleEnd(Http1xClientConnection.java:624)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:77)
	at io.vertx.core.impl.ContextImpl.execute(ContextImpl.java:267)
	at io.vertx.core.http.impl.Http1xClientConnection.handleResponseEnd(Http1xClientConnection.java:858)
	at io.vertx.core.http.impl.Http1xClientConnection.handleHttpMessage(Http1xClientConnection.java:730)
	at io.vertx.core.http.impl.Http1xClientConnection.handleMessage(Http1xClientConnection.java:694)
	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:155)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1372)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1235)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1284)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by jonrosner** [comment]
Unfortunately, I don't think that with the given information I can solve the problem. Authentik works and I also use HTTPS callbacks in other configurations. Some information that would be valuable:

- do you use a reverse proxy like Nginx in front of Yaade
- if so, what do the logs say?
- are you sure that your Authentik is configured correctly? Does it work with other services?

**Comment by jonrosner** [comment]
Could you test against a different auth provider (eg. github) with the same configuration of your proxy?

**Comment by luketainton** [comment]
@jonrosner - interestingly I can get it to work w/ Authentik if I make use of its GitHub compatibility endpoints. Not entirely sure what's going on but I'm happy with this setup for now. Thanks for your help 😄
